# Generated by Django 5.2.8 on 2025-11-20 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('tg_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Полное имя')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Username Telegram')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата записи')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Вес')),
                ('calories_consumed', models.PositiveIntegerField(blank=True, null=True, verbose_name='Потреблено калорий')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='bd_client.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Запись прогресса',
                'verbose_name_plural': 'Записи прогресса',
                'ordering': ['-date'],
                'unique_together': {('client', 'date')},
            },
        ),
    ]
