# Generated by Django 5.2.8 on 2025-11-30 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_client', '0001_initial'),
        ('bd_trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='client',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='bd_trainer.trainer', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Полное имя'),
        ),
    ]
