# Generated by Django 5.2.8 on 2025-11-20 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('tg_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Полное имя')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Username Telegram')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Забронирован')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to='bd_trainer.trainer')),
            ],
            options={
                'unique_together': {('trainer', 'start_time')},
            },
        ),
    ]
