# Generated by Django 5.2.8 on 2025-11-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='link_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Код ссылки'),
        ),
    ]
