# Generated by Django 5.2.8 on 2025-11-30 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_trainer', '0002_trainer_link_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availableslot',
            options={'verbose_name': 'Доступный слот', 'verbose_name_plural': 'Доступные слоты'},
        ),
        migrations.RemoveField(
            model_name='availableslot',
            name='end_time',
        ),
        migrations.AddField(
            model_name='availableslot',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Продолжительность (минуты)'),
        ),
        migrations.AlterField(
            model_name='availableslot',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to='bd_trainer.trainer', verbose_name='Тренер'),
        ),
    ]
